output: "{{.Dir}}/readme.md"
repository:
  url: https://github.com/plsmphnx/go-redis-bucket
  defaultBranch: main
  path: /
template:
  doc: |
    {{- range .Blocks -}}
      {{- if eq .Kind "paragraph" -}}
        {{- paragraph .Text -}}
      {{- else if eq .Kind "code" -}}
        {{- codeBlock "go" .Text -}}
      {{- else if eq .Kind "header" -}}
        {{- header .Level .Text -}}
      {{- end -}}
    {{- end -}}
header: |+
  [![Go Report Card](https://goreportcard.com/badge/github.com/plsmphnx/go-redis-bucket)](https://goreportcard.com/report/github.com/plsmphnx/go-redis-bucket)
  [![Go Reference](https://pkg.go.dev/badge/github.com/plsmphnx/go-redis-bucket.svg)](https://pkg.go.dev/github.com/plsmphnx/go-redis-bucket)
footer: |+
  ## Contributing

  This project has adopted the
  [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
  For more information see the
  [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or
  contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any
  additional questions or comments.
